{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cocktail-console.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "cocktail-console.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
{{- /*
  TODO 권한 변경 필요!
*/}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cocktail-console.serviceAccountName" . }}
  labels:
    {{- include "cocktail-console.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
  # name: {{ include "cocktail-console.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "cocktail-console.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
