{{- if ne .Values.auth.authType "disabled" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cocktail-console.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "cocktail-console.labels" . | nindent 4 }}
type: Opaque
data:
{{- if eq .Values.auth.authType "oidc" }}
  auth-key: {{ .Values.auth.authKey | b64enc }}
  enc-key: {{ .Values.auth.encKey | b64enc }}
  user-auth-oidc-client-secret: {{ .Values.auth.clientSecret | b64enc }} 
{{- end }}
{{- end }}